# Generated by Django 5.1 on 2025-12-08 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Entrenamiento_Canino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Entrenamiento_Canino.curso'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ofertas/'),
        ),
    ]
