# Generated by Django 5.1 on 2025-12-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Entrenamiento_Canino', '0002_oferta_curso_oferta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='calificacion',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
