# Generated by Django 5.2.7 on 2025-12-09 00:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Entrenamiento_Canino', '0003_testimonio_calificacion_alter_testimonio_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonio',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
        migrations.RemoveField(
            model_name='testimonio',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='testimonio',
            name='testimonio',
        ),
        migrations.AddField(
            model_name='testimonio',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='contenido',
            field=models.TextField(default='Testimonio temporal', verbose_name='Testimonio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonio',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_Entrenamiento_Canino.curso', verbose_name='Curso relacionado'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 12, 9), verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='calificacion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Calificación'),
        ),
    ]
